# Generated by Django 2.2 on 2020-07-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='This is a slug', unique=True),
            preserve_default=False,
        ),
    ]
