# Generated by Django 2.2 on 2020-07-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='shuvo', unique=True),
            preserve_default=False,
        ),
    ]
